### ISSUE TITLE
Warning on HisPrice string to date time convert

### ISSUE THREAD

**Issue by enxt** [IFFranciscoME/ROandaAPI#3]
Call method HisPrice with this parameters (for example): 

``` R
HisPrices(AccountType="practice", Count=2, DayAlign=17, Granularity="D", Instrument="EUR_USD", TimeAlign="America%2FMexico_City", Token="23lkj23l4j2l4j2l34j2l4j-mytoken")
```

always return "Warning messages":

> Warning messages:
> 1: In strptime(xx, f <- "%Y-%m-%d %H:%M:%OS", tz = tz) :
>   unknown timezone '%d/%m/%y %H:%M:%S'
> 2: In as.POSIXct.POSIXlt(x) : unknown timezone '%d/%m/%y %H:%M:%S'
> 3: In strptime(x, f, tz = tz) : unknown timezone '%d/%m/%y %H:%M:%S'
> 4: In as.POSIXct.POSIXlt(as.POSIXlt(x, tz, ...), tz, ...) :
>   unknown timezone '%d/%m/%y %H:%M:%S'
> 5: In as.POSIXlt.POSIXct(x, tz) : unknown timezone '%d/%m/%y %H:%M:%S'

It's easy to solve replace in line 122:

``` R
Prices$TimeStamp <- as.POSIXct(Prices$TimeStamp,"%d/%m/%y %H:%M:%S",origin="1970-01-01") 
```

to

``` R
Prices$TimeStamp <- as.POSIXct(strptime(Prices$TimeStamp, "%Y-%m-%d %H:%M:%OS"),origin="1970-01-01")
```

but I'm not sure if it's my R configuration problem

**Comment by convergentist** [comment]
I have just changed that line, i found it useful, but no change though. I believe is some kind of system configuration but i just cant find what. If you solved your problem please post the action taken.
