### ISSUE TITLE
Installation nor working

### ISSUE THREAD

**Issue by kirroa786** [IFFranciscoME/ROandaAPI#4]
Hi, 

I am following your install instructions and am getting the following issues:

> InstList     <- data.frame(InstrumentsList(AccountType,Token,AccountID))[,c(1,3)]
>  Show Traceback

 Error in `colnames<-`(`*tmp*`, value = c("Instrument", "DisplayName",  : 
  'names' attribute [4] must be the same length as the vector [3] > Instrument   <- InstList[117,1]
Error: object 'InstList' not found

> PastPriceAPI <- HisPrices(AccountType,Granularity,DayAlign,TimeAlign,Token,Instrument,Start,End)
> Error in HisPrices(AccountType, Granularity, DayAlign, TimeAlign, Token,  : 
>   argument "Count" is missing, with no default
> ?HisPrices
> No documentation for ‘HisPrices’ in specified packages and libraries:
> you could try ‘??HisPrices’

I am specifically interested in intraday historical prices, but can't find any documentation. I am also wondering where to find accountID as I suspect this is incorrect.

Your assistance is greatly appreciated.
Fakir

**Comment by convergentist** [comment]
I believe you missed the actualization text i made in the readme, where i specify the new parameter "Count" that is involved in HisPrices, if you are using dates then add Count = NULL, please read the readme file.

**Comment by kirroa786** [comment]
Thanks for the quick reply.

True that the missing "Count" may be my problem with running HisPrices. However, I think my main problem is that I have an incorrect Account ID, as the InstList command from the ReadMe sample code also fails.

I used the 7 digits from my practice account. Otherwise the only account number I have is more that 7 digits required, for eg. 100-007-xxxxxxxx-003, the xxxx... part is what I used. I interpret the other numbers to be internal codes. Where should I get the account ID from?

Can you update the ReadMe example with the two alternatives for this HisPrices command, i.e. one with start and end dates and one with the Count?

**Comment by convergentist** [comment]
The account ID is just numerical, ask for it in the live chat it should be very quick.  

as for the examples, here they are:

HisPrices(AccountType = "practice", Granularity = "H1", DayAlign = 17, 
                TimeAlign = "America/Monterrey",  Token = OA_Ak, Instrument = "EUR_USD", 
                Start = NULL, End = NULL, Count=200)

HisPrices(AccountType = "practice", Granularity = "H1", DayAlign = 17,
                TimeAlign = "America/Monterrey", Token = OA_Ak, Instrument = "EUR_USD",
                Start = "2016-01-01", End = "2016-02-10", Count=NULL)

One final recommendation, if something is not working at your code, go to the source code here and see how every function was built, that often helps to know what is not ok in your code.
